language: python
dist: xenial  # required for python 3.7+
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
cache: pip
install:
  - pip install .[test]
  - pip install mypy coverage isort flake8 flake8-bugbear pep8-naming
script:
  # Check type hints
  - mypy --ignore-missing-imports .  # numpy etc. misses library stub files

  # Validate import statements sort (standard lib / third-party / first-party)
  - isort --check-only

  # Check for unused symbols/imports and PEP8 formatting.
  - flake8 --version
  - flake8 --disable-noqa

  # Run unit tests (while measuring coverage).
  - coverage run --branch --source . -m pytest
  - coverage report -m --fail-under 85
deploy:
  provider: releases
  on:
    tags: true
